using Godot;
using System;
using System.Data.SqlTypes;

public partial class ItemHammer : Item
{

	/// <summary>
	/// If the hammer is filled or not
	/// </summary>
	private bool filled = true;
	/// <summary>
	/// If the player has swung already
	/// </summary>
	private bool swung = false;
	private bool charged = false;
	/// <summary> If the hitbox has been spawned </summary>
	private bool spawned = false;

	/// <summary> How much the hammer swing is charged </summary>
	private float swing_charge = 0;

	/// <summary>
	/// Destination angle when cane is rotating
	/// </summary>
	private float drag_angle_dest = 0;

	/// <summary> Animation Player </summary>
	private AnimationPlayer animator;

	/// <summary>
	/// How long the hammer must be charged.
	/// </summary>
	private const float CHARGE_LENGTH = 0.6f;
	private const float SWING_LENGTH = 0.1f;
	private const float RECOVERY_LENGTH = 0.25f;

	/// <summary> Max speed while holding hammer </summary>
	private const float SLOWDOWN_WALKING = 250;

	/// <summary>
	/// Hitbox generated by swing
	/// </summary>
	private PackedScene hitbox_prefab;
	public override void _Ready()
	{
		/* Overriding item type and name */
		this.item_type = ItemTypes.Weapon;
		this.item_name = "Bottle Hammer";
		this.item_tooltip = "An unwieldy weapon that does a lot of damage. Hold to charge and release to slam. Must be refilled after each use.";

		/* Getting hitbox */
		this.hitbox_prefab = GD.Load<PackedScene>("res://Hitboxes/HitboxPlayerRectangle.tscn");

		animator = GetNode<AnimationPlayer>("Animator");
		animator.Play("Full");

		/* Calling base constructor */
		base._Ready();
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
		base._Process(delta);
	}
	/// <summary>
	/// Initialize position of item when it is first picked up
	/// </summary>
	/// <param name="owner_player"> Player that is picking up this item </param>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	public override void Handle_Pickup(Player owner_player, Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing)
	{
		/* Store owner */
		this.owner_player = owner_player;
		/* Exit throw state */
		in_throw = false;

		/* Centered on hand */
		this.Position = new Vector2(0, 0);
	}
	/// <summary>
	/// Handles the animation of the item when not acting.
	/// </summary>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	/// <param name="delta"> Time elapsed since the previous frame, cast to a float </param>
	/// <returns> Vector2 representing new player velocity. </returns>
	public override (Vector2, Vector2, Vector2) Handle_Animation_Default(float delta, Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing)
	{

		/* Hammer  'drags behind' player */
		float player_angle = Mathf.PosMod(player_facing.Angle() + Mathf.Pi / 4, Mathf.Pi * 2);
		if (player_angle < 6 * Mathf.Pi / 4 && player_angle >= 4 * Mathf.Pi / 4)
		{
			Scale = new Vector2(-2, 2);
			drag_angle_dest = player_angle - 1 * Mathf.Pi / 4;
		}
		else
		{
			Scale = new Vector2(2, 2);
			drag_angle_dest = player_angle - 3 * Mathf.Pi / 4;
		}


		/* Lerp towards desired angle */
		this.Rotation = Mathf.LerpAngle(this.Rotation, drag_angle_dest, delta * 15);

		/* Place in front of or behind player depending on rotation  TODO: perhaps easier way to calculate this? */
		if (Mathf.Abs((this.Rotation % (Mathf.Pi * 2) + Mathf.Pi * 2) % (Mathf.Pi * 2) - Mathf.Pi) < Mathf.Pi / 2)
		{
			ZIndex = 1;
		}
		else
		{
			ZIndex = -1;
		}

		/* Calculate hand positions */
		Vector2 hand_left_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 3;
		Vector2 hand_right_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 18;

		/* Slower while holding */
		if (movement_vector.Length() > SLOWDOWN_WALKING)
		{
			movement_vector = movement_vector.Normalized() * SLOWDOWN_WALKING;
		}
		return (movement_vector, hand_left_potential, hand_right_potential);
	}
	/// <summary>
	/// Called when an action is initialized to reset action states and the like.
	/// </summary>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	/// <returns> Returns true if an action is started, false otherwise </returns>
	public override bool Handle_Action_Begin(Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing)
	{
		/* If filled */
		if (filled)
		{
			swung = false;
			charged = false;
			spawned = false;
			swing_charge = 0;

			return true;
		}
		/* Else, don't start action */
		else
		{
			if (owner_player.Get_Authority())
			{
				GameManager.Instance.Display_Message("Refill hammer  to use", 2);
			}
			return false;
		}
	}

	/// <summary>
	/// Handles the use and animation of the item when acting
	/// </summary>
	/// <param name="delta"> Time elapsed since the previous frame, cast to a float </param>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	/// <param name="action_pressed""> If the action button is currently pressed </param>
	/// <returns>
	/// Vector2 representing new player velocity while acting.
	/// Vector2 representing new player facing direction while acting.
	/// Boolean representing if the player should be returned to free movement.
	/// </returns>
	public override (Vector2, Vector2, bool, Vector2, Vector2) Handle_Action(float delta, Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing, bool action_pressed)
	{

		/* Calculate hand positions */
		Vector2 hand_left_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 3;
		Vector2 hand_right_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 18;

		/* Drastically slow down player */
		if (movement_vector.Length() > 50)
		{
			movement_vector = 50 * movement_vector.Normalized();
		}


		/* Place in front of or behind player depending on rotation  TODO: perhaps easier way to calculate this? */
		if (Mathf.Abs((this.Rotation % (Mathf.Pi * 2) + Mathf.Pi * 2) % (Mathf.Pi * 2) - Mathf.Pi) < Mathf.Pi / 2)
		{
			ZIndex = 1;
		}
		else
		{
			ZIndex = -1;
		}

		/* Update player_facing */
		player_facing = face_input_vector.Normalized();
		/* Continuing to charge */
		if (action_pressed && !swung)
		{
			/* Progress through swring */

			swing_charge = Mathf.Min(swing_charge + delta, CHARGE_LENGTH);
			float player_angle = Mathf.PosMod(player_facing.Angle() + Mathf.Pi / 4, Mathf.Pi * 2);
			if (player_angle < 6 * Mathf.Pi / 4 && player_angle >= 4 * Mathf.Pi / 4)
			{
				Scale = new Vector2(-2, 2);
				this.Rotation = player_angle - 1 * Mathf.Pi / 4
				- Mathf.Pi / 2 * swing_charge / CHARGE_LENGTH;
			}
			else
			{
				Scale = new Vector2(2, 2);
				this.Rotation = player_angle - 3 * Mathf.Pi / 4
				+ Mathf.Pi / 2 * swing_charge / CHARGE_LENGTH;
			}

			/* Flashing */
			if (swing_charge == CHARGE_LENGTH && !charged)
			{
				charged = true;
				this.Modulate = new Color(167.0f / 255.0f, 74.0f / 255.0f, 199.0f / 255.0f, 1);
				Tween tween = GetTree().CreateTween();
				tween.TweenProperty(this, "modulate", new Color(1, 1, 1, 1), 0.2f);
			}
			return (movement_vector, player_facing, false, hand_left_potential, hand_right_potential);
		}
		/* Releasing */
		else
		{
			if (swing_charge >= CHARGE_LENGTH)
			{
				if (!swung)
				{
					swung = true;
					/* Play sound */
					sound_player.Play_Effect("Empty", -15, 0.8f);
				}
				swing_charge += delta;
				float player_angle = Mathf.PosMod(player_facing.Angle() + Mathf.Pi / 4, Mathf.Pi * 2);
				if (player_angle < 6 * Mathf.Pi / 4 && player_angle >= 4 * Mathf.Pi / 4)
				{
					Scale = new Vector2(-2, 2);
					this.Rotation = player_angle - 4 * Mathf.Pi / 4
					- Mathf.Pi * 0.8f * Mathf.Min(swing_charge - CHARGE_LENGTH, SWING_LENGTH) / SWING_LENGTH;
				}
				else
				{
					Scale = new Vector2(2, 2);
					this.Rotation = player_angle - 2 * Mathf.Pi / 4
					 + Mathf.Pi * 0.8f * Mathf.Min(swing_charge - CHARGE_LENGTH, SWING_LENGTH) / SWING_LENGTH;
				}

				if (swing_charge >= CHARGE_LENGTH + SWING_LENGTH && !spawned)
				{
					spawned = true;

					/* Only create if owner player is authority */
					if (owner_player.Get_Authority())
					{
						/* TODO: Hitbox of swing, move this earlier and clean up hitbox calculations? */
						var inst = hitbox_prefab.Instantiate<HitboxPlayerRectangle>();
						WORLD.CallDeferred("add_child", inst);
						inst.Initialize(owner_player, 300, 160, this.GlobalPosition + 75 * Vector2.FromAngle(player_angle - Mathf.Pi / 4).Normalized(), player_angle - Mathf.Pi / 4, 0.1f);
					}
					/* Screen shake */
					foreach (PlayerCamera camera in GameManager.Instance.Get_Player_Bag().GetAllCameras())
					{
						camera.Shake(0.5f, 20, 5);
					}

					/* Unfill */
					animator.Play("Empty");
					filled = false;
				}
				/* Finishing swing */
				if (swing_charge >= CHARGE_LENGTH + SWING_LENGTH + RECOVERY_LENGTH)
				{
					return (movement_vector, player_facing, true, hand_left_potential, hand_right_potential);
				}
				else
				{
					/* Continue swing */
					return (movement_vector, player_facing, false, hand_left_potential, hand_right_potential);
				}
			}
			else
			{
				return (movement_vector, player_facing, true, hand_left_potential, hand_right_potential);
			}
		}


	}

	/// <summary>
	/// Fills the hammer
	/// </summary>
	public void Fill()
	{
		if (!filled)
		{
			/* Play sound */
			sound_player.Play_Effect("Fill", -3);
		}
		filled = true;
		animator.Play("Full");
	}
}
