using System;
using Godot;

/// <summary>
/// Candy Cane item.
/// </summary>
public partial class ItemCandyCane : Item
{

	/// <summary>
	/// Destination angle when cane is rotating
	/// </summary>
	private float drag_angle_dest = 0;

	/// <summary>
	/// Current side the cane is on (-1 or 1).
	/// </summary>
	private float swing_side = -1f;

	/// <summary>
	/// Progress through the swing.
	/// </summary>
	private float swing_progress = 0f;

	/// <summary>
	/// Time until the cane can be swung again
	/// </summary>
	private float recovery_timer = 0f;

	/// <summary>
	/// Cooldown between each swing.
	/// </summary>
	private const float RECOVERY_TIME = 0.7f;


	/// <summary>
	/// Angle (from directly backwards) that cane is held at.
	/// </summary>
	private const float SWORD_HELD_ANGLE = 0.1f;

	/// <summary>
	/// Length of swing windup.
	/// </summary>
	private const float SWING_WINDUP_LENGTH = 0.15f;

	/// <summary>
	/// Length of swing.
	/// </summary>
	private const float SWING_SWING_LENGTH = 0.1f;

	/// <summary>
	/// Hitbox generated by swing
	/// </summary>
	private PackedScene hitbox_prefab;
	private PackedScene arc_prefab;
	public override void _Ready()
	{
		/* Overriding item type and name */
		this.item_type = ItemTypes.Weapon;
		this.item_name = "Candy Cane";
		this.item_tooltip = "Long and sharp, swings in a long wide arc. Click to use.";
		arc_prefab = GD.Load<PackedScene>("res://Player/PlayerItems/CandyCane/CandyScytheArc.tscn");
		/* Getting hitbox */
		this.hitbox_prefab = GD.Load<PackedScene>("res://Hitboxes/HitboxPlayerRectangle.tscn");

		/* Calling base constructor */
		base._Ready();
	}

	public override void _Process(double delta)
	{
		base._Process(delta);

		/* Decrease recovery timer */
		this.recovery_timer = Mathf.Max(0, this.recovery_timer - (float)delta);
	}

	/// <summary>
	/// Initialize position of item when it is first picked up
	/// </summary>
	/// <param name="owner_player"> Player that is picking up this item </param>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	public override void Handle_Pickup(Player owner_player, Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing)
	{
		/* Store owner */
		this.owner_player = owner_player;
		/* Exit throw state */
		in_throw = false;

		/* Centered on hand */
		this.Position = new Vector2(0, 0);

		/* Reset swing side */
		swing_side = -1f;
		this.Scale = new Vector2(-swing_side * Mathf.Abs(this.Scale.X), Mathf.Abs(this.Scale.Y));

		drag_angle_dest = player_facing.Angle() - Mathf.Pi / 2 + Mathf.Pi * SWORD_HELD_ANGLE * swing_side;
	}

	/// <summary>
	/// Handles the animation of the item when not acting.
	/// </summary>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	/// <param name="delta"> Time elapsed since the previous frame, cast to a float </param>
	/// <returns> Vector2 representing new player velocity. </returns>
	public override (Vector2, Vector2, Vector2) Handle_Animation_Default(float delta, Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing)
	{

		/* Cane 'drags behind' player */
		drag_angle_dest = player_facing.Angle() - Mathf.Pi / 2 + Mathf.Pi * SWORD_HELD_ANGLE * swing_side;

		/* Lerp towards desired angle */
		this.Rotation = Mathf.LerpAngle(this.Rotation, drag_angle_dest, delta * 15);

		/* Place in front of or behind player depending on rotation  TODO: perhaps easier way to calculate this? */
		if (Mathf.Abs((this.Rotation % (Mathf.Pi * 2) + Mathf.Pi * 2) % (Mathf.Pi * 2) - Mathf.Pi) < Mathf.Pi / 2)
		{
			ZIndex = 1;
		}
		else
		{
			ZIndex = -1;
		}

		/* Calculate hand positions */
		Vector2 hand_left_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 3;
		Vector2 hand_right_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 18;

		/* No effect on movement */
		return (movement_vector, hand_left_potential, hand_right_potential);
	}

	/// <summary>
	/// Called when an action is initialized to reset action states and the like.
	/// </summary>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	/// <returns> Returns true if an action is started, false otherwise </returns>
	public override bool Handle_Action_Begin(Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing)
	{
		/* If not in recovery */
		if (recovery_timer <= 0)
		{
			/* Reset animation progress and hard set angle */
			this.Rotation = player_facing.Angle() - Mathf.Pi / 2 + Mathf.Pi * SWORD_HELD_ANGLE * swing_side;
			swing_progress = 0;

			return true;
		}
		/* Else, don't start action */
		else
		{
			return false;
		}
	}

	/// <summary>
	/// Handles the use and animation of the item when acting
	/// </summary>
	/// <param name="delta"> Time elapsed since the previous frame, cast to a float </param>
	/// <param name="move_input_vector"> Player movement vector of current frame </param>
	/// <param name="face_input_vector"> Player facing vector of the current frame. </param> 
	/// <param name="movement_vector"> Player movement vector of current frame </param>
	/// <param name="player_facing"> Direction that the player is currently facing </param>
	/// <param name="action_pressed""> If the action button is currently pressed </param>
	/// <returns>
	/// Vector2 representing new player velocity while acting.
	/// Vector2 representing new player facing direction while acting.
	/// Boolean representing if the player should be returned to free movement.
	/// </returns>
	public override (Vector2, Vector2, bool, Vector2, Vector2) Handle_Action(float delta, Vector2 move_input_vector,
		Vector2 face_input_vector, Vector2 movement_vector, Vector2 player_facing, bool action_pressed)
	{
		/* TODO: Allow reangling while in swing? */

		/* Progress through swring */
		swing_progress += delta;

		/* Calculate hand positions */
		Vector2 hand_left_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 3;
		Vector2 hand_right_potential = this.Position + Vector2.FromAngle(this.Rotation - Mathf.Pi / 2) * 18;

		/* Drastically slow down player */
		if (movement_vector.Length() > 50)
		{
			movement_vector = 50 * movement_vector.Normalized();
		}


		/* Place in front of or behind player depending on rotation  TODO: perhaps easier way to calculate this? */
		if (Mathf.Abs((this.Rotation % (Mathf.Pi * 2) + Mathf.Pi * 2) % (Mathf.Pi * 2) - Mathf.Pi) < Mathf.Pi / 2)
		{
			ZIndex = 1;
		}
		else
		{
			ZIndex = -1;
		}


		/* Swing windup */
		if (swing_progress < SWING_WINDUP_LENGTH)
		{
			this.Rotation = player_facing.Angle() - Mathf.Pi / 2 + Mathf.Pi * SWORD_HELD_ANGLE * (1 - 1f * swing_progress / SWING_WINDUP_LENGTH) * swing_side;
			return (movement_vector, player_facing, false, hand_left_potential, hand_right_potential);
		}

		/* Actual swing */
		else if (swing_progress < SWING_SWING_LENGTH + SWING_WINDUP_LENGTH)
		{
			/* Play sound here */
			if (swing_progress - delta <= SWING_WINDUP_LENGTH)
			{
				sound_player.Play_Effect("Swing");
				/* Spawn scythe arc */
				var arc_inst = arc_prefab.Instantiate<CandyScytheArc>();
				WORLD.CallDeferred("add_child", arc_inst);
				arc_inst.Initialize(this.GlobalPosition + 70 * player_facing.Normalized(), player_facing.Angle());
			}

			/* Update rotation */
			this.Rotation = player_facing.Angle() - Mathf.Pi / 2 + Mathf.Pi * (SWORD_HELD_ANGLE + (2 - 2 * SWORD_HELD_ANGLE) * (swing_progress - SWING_WINDUP_LENGTH) / SWING_SWING_LENGTH) * swing_side;
			return (movement_vector, player_facing, false, hand_left_potential, hand_right_potential);
		}

		/* Completion of swing */
		else
		{
			/* Only create if owner player is authority */
			if (owner_player.Get_Authority())
			{
				/* TODO: Hitbox of swing, move this earlier and clean up hitbox calculations? */
				var inst = hitbox_prefab.Instantiate<HitboxPlayerRectangle>();
				WORLD.CallDeferred("add_child", inst);
				inst.Initialize(owner_player, 240, 160, this.GlobalPosition + 30 * player_facing.Normalized(), player_facing.Angle(), 0.1f);

			}
			/* Swap side of swing */
			swing_side *= -1;
			this.Scale = new Vector2(-swing_side * Mathf.Abs(this.Scale.X), this.Scale.Y);

			swing_progress = 0;

			/* End action and set recovery time */
			recovery_timer = RECOVERY_TIME;
			return (movement_vector, player_facing, true, hand_left_potential, hand_right_potential);
		}


	}
}
